### ISSUE TITLE
Create Deppy Controller

### ISSUE THREAD

**Issue by oceanc80** [operator-framework/deppy#17]
Goal: Create first pass Deppy controller that is responsible for watching the input api and interfacing with the resolver

A/C:
- Collect all cluster inputs
- Translate cluster inputs into satsolver problem
- Output resolution decision someplace

**Comment by akihikokuroda** [comment]
> Translate cluster inputs into satsolver problem

Is this utilize #11?  What is the `satsolver problem`?   Is it https://github.com/joelanford/kuberdep/blob/main/api/v1/problem_types.go?

**Comment by tylerslaton** [comment]
There is some contention around if we even need a controller for this or if the Deppy project will be a library that gets imported by clients that need resolution. For the time being we're going to go ahead and close this issue out until we come to a consensus on design.
