### ISSUE TITLE
Feature Request: Seperate manual installs for manual upgrades

### ISSUE THREAD

**Issue by awgreene** [operator-framework/deppy#27]
Based on the OLM V0 APIs, there [is a desire](https://github.com/operator-framework/operator-lifecycle-manager/issues/2855) to automatically approve the first installation of an operator and then require manual approval on subsequent upgrades. This need should be considered when developing Deppy.

**Comment by tylerslaton** [comment]
Leaving this issue open for now until we get further along in the overall effort of OLM V1. However, this is is not something that falls under Deppy's domain. There is talk around approval logic occurring at a higher level above both RukPak and Deppy which we've thrown around being called the Operator API. However, that is very far down the line of our internal roadmap so we should keep that in mind. Marking this with a label to indicate the fact it should live elsewhere for the time being.

**Comment by m1kola** [comment]
Closed - out of scope for Deppy as explained above
