### ISSUE TITLE
Docs: Update CONTRIBUTING doc to have correct slack channel link

### ISSUE THREAD

**Issue by oceanc80** [operator-framework/deppy#30]
Update [CONTRIBUTING.md](https://github.com/operator-framework/deppy/blob/main/CONTRIBUTING.MD?plain=1#L11) to have the correct slack channel linked now that a [#deppy-dev](https://kubernetes.slack.com/archives/C045L6WK27N) channel has been created.

**Comment by mrajen27** [comment]
Team, I will work on this issue

**Comment by timflannagan** [comment]
Closed by #31
