### ISSUE TITLE
EntityUniverse updates

### ISSUE THREAD

**Issue by perdasilva** [operator-framework/deppy#40]
https://github.com/operator-framework/deppy/pull/37 introduced the `EntityUniverse` as a queryable set of `Entity`s. The current implementation is not thread-safe and will required additional changes, e.g.
 - thread-safety
 - ability to mutate the "universe" (add/remove entities)
 - ability to shard the space over the sources of the entities
 - possibly make it an interface

Depending on how our [design discussions](https://hackmd.io/fDfcLKNzRPCgILMIQ8aPOw#Appendix-III-Deppy-as-a-Framework) go, this may become the `EntitySource` interface.

**Comment by m1kola** [comment]
Obsolete, closing
