### ISSUE TITLE
EntitySource API

### ISSUE THREAD

**Issue by perdasilva** [operator-framework/deppy#43]
#### User Story

As a user I would like to create to provide content to my solver from different sources (e.g. service, file, hard-coded, etc.)

#### Summary / Background

Deppy is a framework for creating constraint solvers over "entities". It is composed of the following components:

1. `Entity`: a structure with an unique string id and a set of properties (map[string]string)
2. `EntitySource`: an interface to a source of entities. It implements an entity query interface that allows consumers to find entities that contain certain properties, sort the result rest on an arbitrary basis, and also group entities by an arbitrary key function (e.g. `GroupBy(func(entity *Entity) string) map[string][]Entity)`)
3. `ConstraintGenerator`: an interface that can produce []solver.Variable given an entity query interface (something that can query over a set of EntitySources`)

#### Acceptance Criteria

 * EntitySource interface defined
 * EntitySource interface allows for querying of the underlying entities:
   * Get all entities
   * Filter entities by predicate(s)
   * Group entities by an arbitrary key function (e.g. `GroupBy(func(entity *Entity) string) map[string][]Entity)`)
   * Can sort result sets by an arbitrary comparison function

#### Scenarios

 * I would like to provide entities that represent bundles in an [OLM CatalogSource](https://olm.operatorframework.io/docs/concepts/crds/catalogsource/)
 * I would like to provide entities from a command-line given [cnf dimacs file](https://jix.github.io/varisat/manual/0.2.0/formats/dimacs.html)
 * I would like to provide hard-coded entities

#### Links (docs, drawings, designs, etc)

[Deppy-as-a-Framework](https://hackmd.io/fDfcLKNzRPCgILMIQ8aPOw?view#Appendix-III-Deppy-as-a-Framework)

#### Definition of Done
 * unit tests
 * extensive godoc (this is a framework after all)
 * reviewed and merged

**Comment by akihikokuroda** [comment]
I looked at the example.  I wonder if we can separate the interface used by the solverAPI and interface provided by the entity source (deppysource)?   The Get, Filter, Groupby and sort are not source type dependent once the entities from the deppy source are cached.   So these functions can be provided in the interface used by the solverAPI without the entitysource interface implementing it.  So the entity source just need to provide the sync function.  WDYT @perdasilva

**Comment by akihikokuroda** [comment]
I put the entitysource interface in the `source` package and also made a use of the `EntityUniverse`.  But it causes **import cycle not allowed** error.  So I had to make the `entitysource` pakage out of the source pakcage.  If the `EntityUniverse` is in the `source` package, I can put the entitysource into the `source` package, too. @perdasilva WDYT

**Comment by m1kola** [comment]
Obsolete, closing
