### ISSUE TITLE
DeppySource Adapter Client

### ISSUE THREAD

**Issue by perdasilva** [operator-framework/deppy#45]
#### User Story

As a user I would like to access the entities I've made available through a deployment of the DeppySource Adapter Server

#### Summary / Background

DeppySource Adapter will be sub-framework of the Deppy framework that will facilitate the transformation of online resource into entities and the querying of those entities

#### Acceptance Criteria

 * Given a host:port, I can communicate with a deployment of the DeppySource Server to get all entities

#### Scenarios

 * I have an [OLM CatalogSource](https://olm.operatorframework.io/docs/concepts/crds/catalogsource/) and would like to provide the contained bundles as entities for resolution
 *  This will probably end up in its own repository eventually, therefore it should be placed in its own package s.t. it can just be yanked from the code-base without side-effects (aside from recalculating project dependencies for go.mod)

#### Links (docs, drawings, designs, etc)

[Deppy-as-a-Framework](https://hackmd.io/fDfcLKNzRPCgILMIQ8aPOw?view#Appendix-III-Deppy-as-a-Framework)

#### Dependencies

Possibly https://github.com/operator-framework/deppy/issues/44, but if we can agree on the interface before hand, we can do this in tandem

#### Definition of Done

 * unit tests
 * extensive godoc (this is a framework after all)
 * documentation of design/architecture as needed
 * reviewed and merged

**Comment by m1kola** [comment]
Obsolete, closing
