### ISSUE TITLE
DeppySource

### ISSUE THREAD

**Issue by perdasilva** [operator-framework/deppy#46]
#### User Story

As a user I would like to provide the entities served by my DeppySource Server deployment to the constraints api and solver

#### Summary / Background

DeppySource will be sub-framework of the Deppy framework that will facilitate the transformation of online resource into entities and the querying of those entities

#### Acceptance Criteria

 * Implements EntitySource interface
 * Provides client-side querying of the entities provided by the deppy source (acquired through the DeppySource Server client)
 * Created from host:port of the DeppySource Server

#### Scenarios

 * I have an [OLM CatalogSource](https://olm.operatorframework.io/docs/concepts/crds/catalogsource/) and would like to provide the contained bundles as entities for resolution
 * This will probably end up in its own repository eventually, therefore it should be placed in its own package s.t. it can just be yanked from the code-base without side-effects (aside from recalculating project dependencies for go.mod)

#### Links (docs, drawings, designs, etc)

[Deppy-as-a-Framework](https://hackmd.io/fDfcLKNzRPCgILMIQ8aPOw?view#Appendix-III-Deppy-as-a-Framework)

#### Dependencies

 * https://github.com/operator-framework/deppy/issues/44
 * https://github.com/operator-framework/deppy/issues/45

If the client interface is agreed on before hand, these could be done in tandem

#### Definition of Done
 * unit tests
 * integration tests (should be ok to create a mock service directly from the test)
 * extensive godoc (this is a framework after all)
 * reviewed and merged

**Comment by m1kola** [comment]
Obsolete, closing
