### ISSUE TITLE
DeppySource Framework Documentation

### ISSUE THREAD

**Issue by perdasilva** [operator-framework/deppy#48]
#### User Story

As a user I would like to have all the information I need to create my own DeppySource

#### Summary / Background

DeppySource is a framework for creating online EntitySources for querying by the Deppy API

#### Acceptance Criteria

 * APIs documented
 * example(s) given

#### Links (docs, drawings, designs, etc)

[Deppy-as-a-Framework](https://hackmd.io/fDfcLKNzRPCgILMIQ8aPOw?view#Appendix-III-Deppy-as-a-Framework)

#### Definition of Done

 * Readme with a quick start guide
 * reviewed and merged

**Comment by m1kola** [comment]
Obsolete, closing
