### ISSUE TITLE
CatalogSource DeppySource

### ISSUE THREAD

**Issue by perdasilva** [operator-framework/deppy#49]
#### User Story

As a user I would like to provide the entities served by my [CatalogSource](https://olm.operatorframework.io/docs/concepts/crds/catalogsource/) to the solver

#### Summary / Background

DeppySource will be sub-framework of the Deppy framework that will facilitate the transformation of online resource into entities and the querying of those entities.

[CatalogSource](https://olm.operatorframework.io/docs/concepts/crds/catalogsource/) is a format for distributing operators on kubernetes

#### Acceptance Criteria

 * Translates CatalogSource  content into Entities
 * Entities contain all the information necessary for building constraints (dependency relationships, generic properties, channel and upgrade graph properties, default channel
 * This will probably end up in its own repository eventually, therefore it should be placed in its own package s.t. it can just be yanked from the code-base without side-effects (aside from recalculating project dependencies for go.mod)

#### Scenarios

 * I have an [OLM CatalogSource](https://olm.operatorframework.io/docs/concepts/crds/catalogsource/) and would like to provide the contained bundles as entities for resolution

#### Links (docs, drawings, designs, etc)

[Deppy-as-a-Framework](https://hackmd.io/fDfcLKNzRPCgILMIQ8aPOw?view#Appendix-III-Deppy-as-a-Framework)

#### Dependencies

 * https://github.com/operator-framework/deppy/issues/44

#### Definition of Done
 * unit tests
 * integration tests (should be ok to create a mock service directly from the test)
 * extensive godoc (this is a framework after all)
 * reviewed and merged

**Comment by m1kola** [comment]
OLM specific, we want deppy to be independed from OLM details. Also OLM already has something similar in operator-controller. Closing
